# this is a non-dendritic nix class module file.
# automatically discovered by `den.import-tree` as enabled in auto-imports.nix
#
# suppose this file was auto-generated by nixos-generate-config or some other hardware tooling.
{

}
