# this is a non-dendritic nix class module file.
# automatically discovered by `den.import-tree` as enabled in auto-imports.nix
#
# USER TODO: Remove this file.
# suppose this file was auto-generated by nixos-generate-config or some other hardware tooling.
{ lib, ... }:
{
  # used in CI to test this file was actually imported.
  options.auto-imported = lib.mkOption {
    readOnly = true;
    type = lib.types.bool;
    default = true;
  };
}
