name: GH Pages
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["docs/**"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  versioned:
    runs-on: ubuntu-latest
    outputs:
      artifactIds: ${{ steps.artifactIds.outputs.artifactIds }}
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - run: gh api "/repos/$GITHUB_REPOSITORY/actions/artifacts" | tee ~/artifacts.json
      - run: jq -r '.artifacts | map({id,name} | select(.name | match("docs-"))) | group_by(.name) | map(.[0]) ~/artifacts.json | tee ~/docs.json
      - id: artifactIds
        run: |
          jq -r 'map(.id) | join(",")' ~/docs.json | tee ~/artifactIds
          echo "artifactIds=$(cat ~/artifactIds)" | tee $GITHUB_OUTPUT
      - id: versions
        run: |
          jq -r 'map(.name | sub("docs-";"")) | join(",")' ~/docs.json | tee ~/versions
          echo "versions=$(cat ~/versions)" | tee $GITHUB_OUTPUT
  deploy:
    needs: [versioned]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Build
        run: |
          pushd docs
          pnpm install
          pnpm run build
          popd
      - run: echo "${{needs.versioned.outputs.versions}}" | tee docs/dist/versions
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{needs.versioned.outputs.artifactIds}}
          path: "./docs/dist"
          merge-multiple: true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
