name: GH Pages
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["docs/**"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/versioned/docs
      - run: gh api "/repos/$GITHUB_REPOSITORY/actions/artifacts" | tee ~/versioned/artifacts.json
      - run: jq -r '.artifacts | map({id,name} | select(.name | match("docs-"))) | group_by(.name) | map(.[0])' ~/versioned/artifacts.json | tee ~/versioned/docs.json
      - run: |
          for id in $(jq -r 'map(.id)|.[]'  ~/versioned/docs.json); do
            gh api "/repos/$GITHUB_REPOSITORY/actions/artifacts/${id}/zip" > ~/versioned/${id}.zip
            unzip -u -d ~/versioned/docs ~/versioned/${id}.zip
          done
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Build
        run: |
          pushd docs
          pnpm install
          pnpm run build
          popd
      - run: cp -r ~/versioned/docs/* docs/dist/
      - run: cp ~/versioned/docs.json docs/dist/versions.json
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
